version: '3.8'
services:
  backend:
    build:
      context: .
    container_name: node-app
    volumes:
      - myvolume:/app
    networks:
      - mynetwork
    ports:
      - "3000:3000"

volumes:
  myvolume:

networks:
  mynetwork:
