version: "3.8"
services: 
  nginx:
    build:
      context: ./nginx
    container_name: nginx_cont
    ports:
      - "80:80"
    restart: always
    networks:
      - notes-app 
    depends_on:
      - django

  django:
    build:
      context: .
    container_name: django_cont
    command: sh -c "python manage.py migrate --no-input &&  gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - notes-app
    env_file:
      - ".env"
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - notes-app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  mysql-data:

networks:
  notes-app:

