version: '3.3'
services:
  backend:
    build:
      context: .
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
